### ISSUE TITLE
Embargoable.apply_embargo does not save the embargo that it creates

### ISSUE THREAD

**Issue by flyingzumwalt** [samvera/hydra-head#226]
I'm not sure if this is a bug.  Here's the situation:

``` ruby
curation_concern.apply_embargo(attrs_that_trigger_creating_an_embargo)
curation_concern.save
curation_concern.under_embargo? 
=> true
curation_concern.reload
curation_concern.under_embargo? 
=> false
```

Is that how it should work?  I would expect `curation_concern.apply_embargo` plus `curation_concern.save` to be all I need to do.  Currently I have to do this:

``` ruby
curation_concern.apply_embargo(attrs_that_trigger_creating_an_embargo)
curation_concern.embargo.save
curation_concern.save
```

**Comment by cjcolvar** [comment]
I'm fine with closing this.  Thanks @no-reply for looking into it.  
My guess is that permissions weren't autosaving/autocreating when this issue was opened but was maybe taken care of here (committed in 2016 according to git blame): https://github.com/samvera/hydra-head/blob/master/hydra-access-controls/app/models/concerns/hydra/access_controls/permissions.rb#L12-L15
