### ISSUE TITLE
Use a released version of Blacklight Access Controls

### ISSUE THREAD

**Issue by no-reply** [samvera/hydra-head#461]
### Descriptive summary

The version of `blacklight-access_controls` used in `master` is `0.7.0-rc1`. In order to release from `master`, we need it to support at least one released version of each of its dependencies.

**Comment by cjcolvar** [comment]
This seems like a related issue: https://github.com/projectblacklight/blacklight-access_controls/issues/44

**Comment by no-reply** [comment]
@cjcolvar do we want to try to push for a Blacklight release, or is it better to rollback the changes relying on unreleased `blacklight-access_controls` features

**Comment by cjcolvar** [comment]
I think we could own `blacklight-access_controls` if we want.  FWIW, `hydra-head` is the only package with it as a dependency.  All others listed in github are repositories which probably pull it in via `hydra-head`.  So I think it would be fine to push for a release of `blacklight-access_controls`.

**Comment by no-reply** [comment]
should we just inline it?

**Comment by cjcolvar** [comment]
Well, now I'm second guessing since the release notes for `0.7.0.rc1` says there is backwards-incompatible changes in the SearchBuilder `#initialize` method signature.

**Comment by no-reply** [comment]
I see at least a few blacklight (-not-samvera) projects depending on `b-a_c` https://github.com/projectblacklight/blacklight-access_controls/network/dependents

I've submitted a PR that reverts the upgrade to `blacklight-access_controls`.

It looks to me this project has seen two small releases in the last two years, and has had an unreleasable(?) `master` for the majority of that time.

With my Hyrax hat on, I'm thinking I'd like to see one of two outcomes:
  - Inline the parts of `blacklight-access_controls` that we rely into `hydra-access_controls` and remove the dependency.
  - Move `blacklight-access_controls` under the `samvera-labs` namespace, and begin work on moving it into the CCWG's maintenance purview.

**Comment by no-reply** [comment]
cc @jcoyne @cbeer @mark-dce (who else?)

**Comment by jcoyne** [comment]
@no-reply this was extracted from hydra-access_controls by DCE for PSU because there are Blacklight projects that need access control that are not Hydra/Samvera based.  You are welcome to become contributors to blacklight-access_controls though.

**Comment by mark-dce** [comment]
@no-reply echoing @jcoyne above, the extraction work was sponsored by PSU in order to support a blacklight-only front-end that could respect "hydra-access_controls" style access permissions.  I think that other institutions like Tufts Universtiy and UCLA may have plans to implement blacklight-based read-only discovery applications that expose content created in Hyrax.  They would also need capabilities similar to the ones [blacklight-access_controls](https://github.com/projectblacklight/blacklight-access_controls) provides.

We may want to revisit whether we consider `blacklight-access-controls` a Blacklight community resource or a Samvera community resource - I think we initially leaned toward having it managed by the Blacklight community figuring it would need to track Blacklight releases more closely than Samvera releases. 

Tagging @cam156 to get PSU's input on the topic.  

For now the inline solution seems like a good path to keep momentum on Hyrax, but we may want to revisit how we keep the inline code coordinated with blacklight applications that want to read from hyrax generated access controls.
